# Generated by Django 5.2.8 on 2025-11-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do treinador.', max_length=100)),
                ('idade', models.IntegerField(help_text='Idade do treinador.')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro.')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Data da última atualização do registro.')),
            ],
            options={
                'verbose_name': 'Treinador',
                'verbose_name_plural': 'Treinadores',
                'ordering': ['nome'],
            },
        ),
    ]
