# Generated by Django 5.2.8 on 2025-11-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
        ('treinadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinador',
            name='pokemons',
            field=models.ManyToManyField(blank=True, related_name='treinadores', to='pokemons.pokemon'),
        ),
    ]
