# Generated by Django 5.2.8 on 2025-11-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Pokémon, usado para buscar na PokeAPI', max_length=100, unique=True)),
                ('foto', models.URLField(blank=True, help_text='URL da imagem do Pokémon (decímetros)', null=True)),
                ('altura', models.IntegerField(default=0, help_text='Peso do Pokémon (hectogramas)')),
                ('peso', models.IntegerField(default=0, help_text='Peso do Pokémon(hectogramas)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémons',
                'ordering': ['nome'],
            },
        ),
    ]
